# START:define
require 'rubygems'
require 'ribs'

Ribs::DB.define do |db|
  db.dialect = 'Derby'
  db.uri = 'jdbc:derby:using_jruby;create=true'
  db.driver = 'org.apache.derby.jdbc.EmbeddedDriver'
end
# END:define

# START:raw
Ribs::with_handle do |h|
  h.ddl "DROP TABLE book" rescue nil

  h.ddl <<SQL
CREATE TABLE book (
  id INT NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 1, INCREMENT BY 1),
  title VARCHAR(255) NOT NULL,
  author VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
)
SQL

  stmt = "INSERT INTO book(title, author) VALUES(?, ?)"
  h.insert(stmt,
           ["To Say Nothing Of The Dog", "Connie Willis"],
           ["A Confederacy Of Dunces", "John Kennedy Toole"],
           ["Ender's Game", "Orson Scott Card"])

  p h.select("SELECT * FROM book")
end
# END:raw

# START:class
class Book
  attr_accessor :id, :title, :author
end

p R(Book).all
# END:class

# START:manipulate
dog = R(Book).get(1)
dog.title += ": How We Found the Bishop's Bird Stump at Last"
R(dog).save
# END:manipulate

# START:create
R(Book).create :id => 4,
               :title => "Goedel, Escher, Bach",
               :author => "Douglas Hofstadter"
# END:create

# START:new
snow = Book.new
snow.id = 5
snow.title = "Snow Crash"
snow.author = "Neal Stephenson"
R(snow).save
# END:new

# START:destroy
R(snow).destroy!
# END:destroy

p R(Book).all
